package Menu;

import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.text.ParseException;

/**
 *
 * @author Vitalik
 */
public class Look extends javax.swing.JInternalFrame {

    mySQL SQL = null;
    String tbl;
    javax.swing.JDesktopPane Fon;

    public Look(javax.swing.JDesktopPane fon, String Name, String tbl, String Title1, String Title2, String Title3, String Title4, String Title5, String Title6, String Title7, String Title8) {
        initComponents();
        this.setTitle(Name);
        this.Fon = fon;
        jTableRezult.setEnabled(false);
        this.tbl = tbl;
        Load(tbl, Title1, Title2, Title3, Title4, Title5, Title6, Title7, Title8);
        if (MainMenu.jMenuItem2.getText().equals("Вийти")) {
            Admin();
        }
    }

    private void Load(String tbl, String Title1, String Title2, String Title3, String Title4, String Title5, String Title6, String Title7, String Title8) {
        SQL = new mySQL(
                "127.0.0.1",
                "3306",
                "athlethic_base_club_data",
                "root",
                "",
                tbl
        );

        String rez = SQL.Conect();
        int i = 0, ii = 1;
        if (rez.equals("Ok")) {

            //заповнюємо таблицю
            ResultSet X = SQL.GetDataSet();
            try {
                ResultSetMetaData colonki = X.getMetaData();
                i = colonki.getColumnCount();
                javax.swing.table.DefaultTableModel dtm = new javax.swing.table.DefaultTableModel();
                String nazvaKolonki[] = new String[i];
                nazvaKolonki[0] = Title1;
                nazvaKolonki[1] = Title2;
                nazvaKolonki[2] = Title3;
                nazvaKolonki[3] = Title4;
                nazvaKolonki[4] = Title5;
                nazvaKolonki[5] = Title6;
                nazvaKolonki[6] = Title7;
                nazvaKolonki[7] = Title8;

                dtm.setColumnIdentifiers(nazvaKolonki);
                dtm.setRowCount(0);//
                while (X.next()) {
                    dtm.setRowCount(dtm.getRowCount() + 1);
                    if (tbl.equals("tbl_coach")) {
                        for (int j = 1; j <= i; j++) {
                            String g = X.getString(j);
                            if (j == 4) {
                                SQL = new mySQL("127.0.0.1", "3306", "athlethic_base_club_data", "root", "", "tbl_rank");
                                rez = SQL.Conect();
                                if (rez.equals("Ok")) {
                                    dtm.setValueAt(SQL.GetSearch("name_ranks", "`id_ranks` = " + g), ii - 1, j - 1);
                                }
                                continue;
                            }
                            dtm.setValueAt(g, ii - 1, j - 1);//виводимо дані у модел
                        }
                        ii++;
                    } else {
                        for (int j = 1; j <= i; j++) {
                            String g = X.getString(j);
                            if (j == 4) {
                                SQL = new mySQL("127.0.0.1", "3306", "athlethic_base_club_data", "root", "", "tbl_category");
                                rez = SQL.Conect();
                                if (rez.equals("Ok")) {
                                    dtm.setValueAt(SQL.GetSearch("name_categorys", "`id_categorys` = " + g), ii - 1, j - 1);
                                }
                                continue;
                            }
                            if (j == 5) {
                                SQL = new mySQL("127.0.0.1", "3306", "athlethic_base_club_data", "root", "", "tbl_coach");
                                rez = SQL.Conect();
                                if (rez.equals("Ok")) {
                                    dtm.setValueAt(SQL.GetSearch("name_coach", "`id_coach` = " + g), ii - 1, j - 1);
                                }
                                continue;
                            }
                            dtm.setValueAt(g, ii - 1, j - 1);//виводимо дані у модел
                        }
                        ii++;
                    }
                }
                jTableRezult.setModel(dtm);
                jTableRezult.setRowHeight(100);
                jTableRezult.getColumn("Фото").setCellRenderer(new CellRenderer());
            } catch (Exception ex) {
                //error
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane = new javax.swing.JScrollPane();
        jTableRezult = new javax.swing.JTable() {
            private static final long serialVersionUID = 1L;

            public boolean isCellEditable(int row, int column) {
                return false;
            };
        };
        jTableRezult.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jPanel2 = new javax.swing.JPanel();
        BtnAddLook = new javax.swing.JButton();
        BtnEditLook = new javax.swing.JButton();
        BtnRemoveLook = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jTableRezult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane.setViewportView(jTableRezult);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Операції", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        BtnAddLook.setEnabled(false);
        BtnAddLook.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BtnAddLook.setText("Додати");
        BtnAddLook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddLookActionPerformed(evt);
            }
        });

        BtnEditLook.setEnabled(false);
        BtnEditLook.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BtnEditLook.setText("Редагувати");
        BtnEditLook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditLookActionPerformed(evt);
            }
        });

        BtnRemoveLook.setEnabled(false);
        BtnRemoveLook.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BtnRemoveLook.setText("Видалити");
        BtnRemoveLook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRemoveLookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnAddLook, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                .addComponent(BtnEditLook, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                .addComponent(BtnRemoveLook, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAddLook)
                    .addComponent(BtnEditLook)
                    .addComponent(BtnRemoveLook))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 789, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAddLookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddLookActionPerformed
        this.dispose();
        if (tbl.equals("tbl_coach")) {
            AddCoach d = new AddCoach(Fon);
            d.setVisible(true);
            Fon.add(d);
        } else {
            AddAthlete d = new AddAthlete(Fon);
            d.setVisible(true);
            Fon.add(d);
        }
    }//GEN-LAST:event_BtnAddLookActionPerformed

    private void BtnEditLookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditLookActionPerformed
        this.dispose();
        int X = jTableRezult.getSelectedRow();
        if (tbl.equals("tbl_coach")) {
            AddCoach d = new AddCoach(Fon);
            try {
                d.Edit((int) Integer.valueOf((String) jTableRezult.getValueAt(X, 0)), (String) jTableRezult.getValueAt(X, 1),
                        (String) jTableRezult.getValueAt(X, 2), (String) jTableRezult.getValueAt(X, 3),
                        (String) jTableRezult.getValueAt(X, 4), (String) jTableRezult.getValueAt(X, 5),
                        (String) jTableRezult.getValueAt(X, 6), (String) jTableRezult.getValueAt(X, 7));
            } catch (ParseException ex) {
                java.util.logging.Logger.getLogger(Look.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            d.setVisible(true);
            Fon.add(d);
        } else {
            AddAthlete d = new AddAthlete(Fon);
            try {
                d.Edit((int) Integer.valueOf((String) jTableRezult.getValueAt(X, 0)), (String) jTableRezult.getValueAt(X, 1),
                        (String) jTableRezult.getValueAt(X, 2), (String) jTableRezult.getValueAt(X, 3),
                        (String) jTableRezult.getValueAt(X, 4), (String) jTableRezult.getValueAt(X, 5),
                        (String) jTableRezult.getValueAt(X, 6), (String) jTableRezult.getValueAt(X, 7));
            } catch (ParseException ex) {
                java.util.logging.Logger.getLogger(Look.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            d.setVisible(true);
            Fon.add(d);
        }

    }//GEN-LAST:event_BtnEditLookActionPerformed

    private void BtnRemoveLookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRemoveLookActionPerformed
        SQL = new mySQL(
                "127.0.0.1",
                "3306",
                "athlethic_base_club_data",
                "root",
                "",
                tbl
        );
        String rez = SQL.Conect();
        if (rez.equals("Ok")) {
            int X;
            X = jTableRezult.getSelectedRow();
            if (X < 0) {
                return;
            }
            X = (int) Integer.valueOf((String) jTableRezult.getValueAt(X, 0));
            Look d = null;
            if (tbl.equals("tbl_coach")) {
                SQL.del(X, "id_coach");
                d = new Look(Fon, "Тренета", "tbl_coach", "Номер тренер", "ПІБ", "День народження", "Звання", "Стаж робот (роки)", "Місце проживання", "Телефон", "Фото");
            } else {
                SQL.del(X, "id_athlete");
                d = new Look(Fon, "Атлети", "tbl_athlete", "Номер атлета", "ПІБ", "День народження", "Розряд", "Тренер", "Місце проживання", "Телефон", "Фото");
            }
            this.dispose();
            d.setVisible(true);
            Fon.add(d);
        }

    }//GEN-LAST:event_BtnRemoveLookActionPerformed

    private void Admin() {
        BtnAddLook.setEnabled(true);
        BtnEditLook.setEnabled(true);
        BtnRemoveLook.setEnabled(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAddLook;
    private javax.swing.JButton BtnEditLook;
    private javax.swing.JButton BtnRemoveLook;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTable jTableRezult;
    // End of variables declaration//GEN-END:variables
}
